name: Ping server

on:
  schedule:
    - cron: '*/1 * * * *'  # каждую минуту

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping 1
        run: curl -s https://collector-bh3t.onrender.com/
      - name: Ping 2
        run: sleep 20 && curl -s https://collector-bh3t.onrender.com/
      - name: Ping 3
        run: sleep 40 && curl -s https://collector-bh3t.onrender.com/
